### PR TITLE
Small README change in usage

### PR DESCRIPTION
**Pull request by jewels86**
I noticed that the usage example had a small python error so I figured I’d fix it!

### CODE REVIEW

**Comment by jewels86** [comment]
One thing: I skimmed through the source code for the `KitikiPlot` class quickly and I thought I saw a line that used `self.data.values`. Python lists don’t have a `values` attribute, so if it is the case that the above line is used, I’ll need to fix the example I edited.

**Comment by BodduSriPavan-111** [comment]
> One thing: I skimmed through the source code for the `KitikiPlot` class quickly and I thought I saw a line that used `self.data.values`. Python lists don’t have a `values` attribute, so if it is the case that the above line is used, I’ll need to fix the example I edited.

Hi @jewels86, <br/><br/> I would like to thank you for making the very first PR for <b>KitikiPlot</b>. Diving deep into the current PR raised,<br/>

1. updating ```javascript``` to ```py``` really promotes better documentation.
2. ```ktk= KitikiPlot( data= # DataFrame or list of sliding window data ) ``` <br/>

**Ans: It can handle either of  ```pd.DataFrame``` or ```list ``` as input**
 
 When we initialize ```KitikiPlot``` class, it follows the below path for initialization of the variable: ```self.data``` <br/>
 
 <i> KitikiPlot -> KitikiCell -> ColorConfig </i>
 
 Inside ColorConfig's ```__init__``` constructor, 
 ```py
# Check if 'data' is of type 'pd.DataFrame' and initialize 'data' attribute.
if isinstance( data, pd.DataFrame):
    self.data= data
    
# Check if 'data' is of type 'list'.
elif isinstance( data, list):

    # Convert 'list' to 'pd.DataFrame' using stride and window_length, and initialize 'data' attribute.
    self.data= self._convert_list_to_dataframe( data, stride, window_length)
```
- If ```pd.DataFrame``` is passed as a value to ```data```, it initializes ```self.data``` with the corresponding input DataFrame
- If  ```list``` is passed then it is converted into a ```pd.DataFrame``` using the static method ```_convert_list_to_dataframe( data: Union[pd.DataFrame, list], stride: int = 1, window_length: int = 10) -> pd.DataFrame```, which utilizes ```stride``` and ```window_length``` parameters.

Thanks,
Boddu Sri Pavan

**Comment by jewels86** [comment]
Thanks for the reply! I missed that part during my quick glance at the code.

**Comment by jewels86** [comment]
I made another small change - I moved the list into the `data` variable.

**Comment by BodduSriPavan-111** [comment]
> I made another small change - I moved the list into the `data` variable.

Yeah, its ok. Merging the PR. 🙂

**Pull request merged**
